---
- name: Configurer Apache sur EC2
  hosts: ec2
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      yum:
        name: "*"
        state: latest

    - name: Installer Apache et PHP
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
        state: present

    - name: Démarrer et activer Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Configurer les autorisations
      file:
        path: /var/www/html
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes